### ISSUE TITLE
Cannot use inline delete button to delete when the records _id property is not an ObjectId

### ISSUE THREAD

**Issue by officert** [officert/mongotron#17]
### Description:

When an object's _id property is not an ObjectId (in this case it was a string), and you try and use the inline delete button, you get an error '{"message":"objectId must be an instance of ObjectId"}'.

<img width="1073" alt="screen shot 2015-11-30 at 1 31 14 pm" src="https://cloud.githubusercontent.com/assets/4620560/11480695/e48ee83c-9766-11e5-92ad-b29eaf2b9a27.png">

### Steps to reproduce:

1) Insert a new object into a collection. Instead of a Mongo ObjectId() for the _id property, use a regular string.
2) Do a find() query on the collection, find the object and hover over it to show the hover menu.
3) Click on the 'X' button to try and delete the record.
4) You should get an error with the message : '{"message":"objectId must be an instance of ObjectId"}'

### Notes:

This is happening because the inline delete is pretty dumb and assumes all records have an _id property and that the property is a Mongo ObjectId().

Can we assume that records will always have an _id property?

**Comment by kbariotis** [comment]
> Can we assume that records will always have an _id property?

MongoDB by default will insert an `_id` field, but still this behavior can be changed. So we cannot assume this.

So, if Mongotron finds an `_id` it can proceed with the deletion. Otherwise, it should deny it because it doesn't have a unique identifier of the document it tries to delete and that may lead to deleting something that the user wasn't intent to.

MongoDB also supports `_id` fields that are not instance of ObjectID. In that case, it should do the deletion regularly since the `_id` index is unique even if it doesn't contain the default ObjectID instances.

**Comment by officert** [comment]
thanks @kbariotis. Just looked at the Mongo docs and looks like all docs must have a unique _id.

https://docs.mongodb.org/manual/reference/glossary/#term-id

So I just got rid of the check that it's an ObjectId. Commit is here:

https://github.com/officert/mongotron/commit/1965f46bfaac768d3291f10ff1ec07692c5c730e
