### ISSUE TITLE
Reduce release app size - remove any unused npm modules and tests etc...

### ISSUE THREAD

**Issue by xaircore** [officert/mongotron#67]
Remove from the release version of the application tests and packages for testing

**Comment by officert** [comment]
@xaircore is this to slim down the size of the releases?

If so I think this is a great idea. Right now the release are pretty huge (OSX is ~130mb which is huggge).

**Comment by xaircore** [comment]
@officert  Yes. It helps reduce size of the distribution, and besides it is idiomatically correct step

**Comment by officert** [comment]
fixed in https://github.com/officert/mongotron/commit/45758fdfb264cdc44078884dc3478d376c40e348

release .zip file sizes are down to :

~53mb for OSX (was 70mb in alpha.2)
~103mb for Linux -x64 (was 132mb in alpha.2)
~52mb for Linux -x32 (was 63mb in alpha.2)
~120mb for Win x64 (was 152mb in alpha.2)
~55mb for Win x32 (was 70mb in alpha.2)
