### ISSUE TITLE
Error opening database

### ISSUE THREAD

**Issue by sergions80** [officert/mongotron#77]
When i try to connect database in MongoLab (MongoDB 3.0) occurs this error:

Error opening database
{"message":"data.copy is not a function"}

v1.0.0-alpha.2

**Comment by officert** [comment]
@sergions80 this is a known issue and has been fixed in master. The fix will be in the next release.

**Comment by jonaswindey** [comment]
Do you know what caused this error? I'm having the same issue but I decided to move away from MongoLab and host the db ourselves.

**Comment by officert** [comment]
@jonaswindey https://github.com/officert/mongotron/issues/63
the issue has to do with the change in authentication mechanisms in MongoDB from 2.0+ to 3.0+. Mongo DB 2.0+ uses ```mongocr``` and 3.0+ uses ```scram-sha-1```. The node [mongo db driver](http://mongodb.github.io/node-mongodb-native/2.1/api/ use )  we're using uses [js-bson](https://github.com/mongodb/js-bson) which is were the issue was. Basically there is a bug/problem when running in node when the ```window``` object is defined, which is the case for Electron applications. So I had to fork the BSON repo and fix it for Electron apps.

**Comment by officert** [comment]
but this has been fixed in the latest release : https://github.com/officert/mongotron/releases/tag/1.0.0-alpha.3

let me know if you have any more issues with it

**Comment by jonaswindey** [comment]
I'm having the issue with iron-node (also an Electron application), used to debug my node applications.

When using mongoose (which uses the mongodb driver, which uses js-bson), I'm getting this error. Tried putting global.window to undefined but without luck.

I'll try to fork mongoose to use your forked version but it seems it always falls back to the default js-bson implementation.

**Comment by officert** [comment]
@jonaswindey I forked the BSON library here https://github.com/officert/js-bson, if you include that as a dependency the issue should go away. Take a look at Mongotron's [package.json](https://github.com/officert/mongotron/blob/master/package.json)

`"bson": "https://github.com/officert/js-bson/tarball/master"`
